# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.2
language: objective-c
# cache: cocoapods
xcode_project: SNavigationControllerExample.xcworkspace
xcode_scheme: SNavigationControllerExample

podfile: Example/Podfile

matrix:
  include:
    - os: osx
      osx_image: xcode9
    - os: osx
      osx_image: xcode9.1
    - os: osx
      osx_image: xcode9.2

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
- pod install --project-directory=Example

script:
- xcodebuild -project Framework/SNavigationController.xcodeproj -target SNavigationController -destination 'platform=iOS Simulator,name=iPhone 6' | xcpretty
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SNavigationControllerExample.xcworkspace -scheme SNavigationControllerExample -destination 'platform=iOS Simulator,name=iPhone 6' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

notifications:
    slack: cyrex-group:ByK4WXNdYYjQ1yYZ2tjDOKyr

after_success:
  - bash <(curl -s https://codecov.io/bash)
